services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./requirements/nginx/ssl:/etc/nginx/ssl
      - wordpress-data:/var/www/html
      - adminer-data:/var/www/adminer
    depends_on:
      - wordpress
      - nextjs
    networks:
      - inception
        

  wordpress:
    build:
      context: ./requirements/wordpress
    ports:
      - "9000:9000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    ports:
      - "3306:3306"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

  bind:
    build:
      context: ./requirements/bind
    ports:
      - 5354:53/udp
      - 5354:53/tcp
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      IP_HOST: ${IP_HOST}
    networks:
      dns:
        ipv4_address: 172.30.0.2

  nextjs:
    build:
      context: ./requirements/nextjs
    ports:
      - "3000:3000"
    networks:
      - inception
  
  redis:
    build:
      context: ./requirements/redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - inception

  adminer:
    build:
      context: ./requirements/adminer
    ports:
      - "8080:8080"
    volumes:
      - adminer-data:/var/www/adminer
    networks:
      - inception
  
  vsftpd:
    build:
      context: ./requirements/vsftpd
    ports:
      - "20-21:20-21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress-data:/var/www/html
    environment:
      FTP_PASSWORD: ${FTP_PASSWORD}
    networks:
      - inception

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${VOLUME_PATH}/wordpress'
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${VOLUME_PATH}/mariadb'
  redis-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${VOLUME_PATH}/redis'
  adminer-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${VOLUME_PATH}/adminer'

networks:
  inception:
    driver: bridge
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.254
