services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
    wordpress_data:
    mariadb_data:

networks:
  network:
    driver: bridge
