services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/ssl:/etc/nginx/ssl
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    ports:
      - "9000:9000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    ports:
      - "3306:3306"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception

  dns:
    build:
      context: ./requirements/dns
    ports:
      - 53:53/udp
      - 53:53/tcp
    environment:
      DNS_DOMAIN: ${DNS_DOMAIN}
      DNS_IP: ${DNS_IP}
    networks:
      - inception

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/tmuramat/data/wordpress'
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/tmuramat/data/mariadb'

networks:
  inception:
    driver: bridge
