services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - wordpress
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./requirements/wordpress/wp_content:/var/www/html
    depends_on:
      - mariadb
    networks:
      - network

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network

volumes:
    wordpress_data:
    mariadb_data:

networks:
  network:
    driver: bridge
