services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - wordpress
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./requirements/wordpress/wp_content:/var/www/html
    depends_on:
      - mariadb
    networks:
      - network

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
    wordpress_data:
    mariadb_data:

networks:
  network:
    driver: bridge
